-- ========================================
-- SUPABASE DATABASE SCHEMA SETUP
-- ========================================
-- Run this in Supabase SQL Editor to create all tables

-- 1. Create Users Table (extends auth.users)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  vehicle_model TEXT,
  battery_capacity FLOAT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Trigger Function for New Users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name, avatar_url)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Create Trigger on Auth Users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. Enable RLS on Users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- 5. Create User Policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON users;
DROP POLICY IF EXISTS "Users can insert their own profile." ON users;
DROP POLICY IF EXISTS "Users can update own profile." ON users;

CREATE POLICY "Public profiles are viewable by everyone."
  ON users FOR SELECT
  USING (true);

CREATE POLICY "Users can insert their own profile."
  ON users FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile."
  ON users FOR UPDATE
  USING (auth.uid() = id);

-- 6. Create Chargers Table
CREATE TABLE IF NOT EXISTS public.chargers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location JSONB,
  status TEXT CHECK (status IN ('Available', 'Occupied', 'Offline')) DEFAULT 'Available',
  cost_per_kwh FLOAT DEFAULT 12.0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Bookings Table
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) NOT NULL,
  charger_id BIGINT REFERENCES public.chargers(id) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  energy_kwh FLOAT,
  total_cost FLOAT,
  status TEXT CHECK (status IN ('Pending', 'Confirmed', 'Completed', 'Cancelled')) DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Enable Row Level Security on Bookings
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- 9. Create Booking Policies
DROP POLICY IF EXISTS "Users can view their own bookings." ON bookings;
DROP POLICY IF EXISTS "Users can create bookings." ON bookings;

CREATE POLICY "Users can view their own bookings."
  ON bookings FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create bookings."
  ON bookings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 10. Insert Sample Chargers
INSERT INTO public.chargers (name, location, status, cost_per_kwh)
VALUES
  ('Community Charger A', '{"lat": 12.9716, "lng": 77.5946}', 'Available', 10.0),
  ('Community Charger B', '{"lat": 12.9718, "lng": 77.5948}', 'Occupied', 12.0),
  ('Tech Park Fast Charger', '{"lat": 12.9352, "lng": 77.6245}', 'Available', 15.0)
ON CONFLICT DO NOTHING;
