const { createClient } = require('@supabase/supabase-js');

// Check arguments
if (process.argv.length < 4) {
    console.log('Usage: node create_tables.js <SUPABASE_URL> <SERVICE_ROLE_KEY>');
    process.exit(1);
}

const supabaseUrl = process.argv[2];
const serviceRoleKey = process.argv[3];

console.log('Creating tables in Supabase...');

const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: {
        autoRefreshToken: false,
        persistSession: false
    }
});

async function createTables() {
    // Create chargers table
    const { error: chargersError } = await supabase.rpc('exec_sql', {
        sql: `
      create table if not exists public.chargers (
        id bigint generated by default as identity primary key,
        name text not null,
        location jsonb,
        status text check (status in ('Available', 'Occupied', 'Offline')) default 'Available',
        cost_per_kwh float default 12.0,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `
    });

    if (chargersError) {
        console.error('Note: Using direct query method instead...');

        // Alternative: Use the SQL Editor API endpoint
        const response = await fetch(`${supabaseUrl}/rest/v1/rpc/exec_sql`, {
            method: 'POST',
            headers: {
                'apikey': serviceRoleKey,
                'Authorization': `Bearer ${serviceRoleKey}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                query: `
          -- Create chargers table
          create table if not exists public.chargers (
            id bigint generated by default as identity primary key,
            name text not null,
            location jsonb,
            status text check (status in ('Available', 'Occupied', 'Offline')) default 'Available',
            cost_per_kwh float default 12.0,
            created_at timestamp with time zone default timezone('utc'::text, now()) not null
          );

          -- Create bookings table
          create table if not exists public.bookings (
            id bigint generated by default as identity primary key,
            user_id uuid references public.users(id) not null,
            charger_id bigint references public.chargers(id) not null,
            start_time timestamp with time zone not null,
            end_time timestamp with time zone not null,
            energy_kwh float,
            total_cost float,
            status text check (status in ('Pending', 'Confirmed', 'Completed', 'Cancelled')) default 'Pending',
            created_at timestamp with time zone default timezone('utc'::text, now()) not null
          );

          -- Enable RLS on bookings
          alter table public.bookings enable row level security;

          -- Drop existing policies if they exist
          drop policy if exists "Users can view their own bookings." on bookings;
          drop policy if exists "Users can create bookings." on bookings;

          -- Create policies
          create policy "Users can view their own bookings."
            on bookings for select
            using ( auth.uid() = user_id );

          create policy "Users can create bookings."
            on bookings for insert
            with check ( auth.uid() = user_id );

          -- Insert dummy chargers
          insert into public.chargers (name, location, status, cost_per_kwh)
          values
            ('Community Charger A', '{"lat": 12.9716, "lng": 77.5946}', 'Available', 10.0),
            ('Community Charger B', '{"lat": 12.9718, "lng": 77.5948}', 'Occupied', 12.0)
          on conflict do nothing;
        `
            })
        });

        console.log('Tables creation initiated via API');
        console.log('Status:', response.status);
    }

    console.log('Done! Tables should be created now.');
}

createTables().catch(console.error);
